# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://xiechenhao.github.io/
date_format: "ordinal"
title: Sociopath&Psychopath
subtitle: "空"
description: "这里是一个博客"
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: xiechenhao

github_username: xiechenhao
location: Shanghai, China


# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: xiechenhao/xiechenhao.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#    username: xiechenhao
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: xiechenhao
#    repo: blog-comments
#   oauth:
#        client_id: e24fc33638569db34ccc
        client_secret: f8f2f7c71f3b83d54af4866f399c405e1e4d3389
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: xiechenhao
    repo: blog-comments
    clientID: e24fc33638569db34ccc
    clientSecret: 4ac15c3415618594091a553f09b2e5f100655ecd
# 在使用其它评论组件时可点击显示 Disqus
#lazy_load_disqus : true#

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
